server:
  port: 8081

spring:
  application:
    name: deal

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /api-docs
    packages-to-scan:
      - com.deal.controllers

  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs/swagger-config
